apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-plus-plus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chat-plus-plus.labels" . | nindent 4 }}
data:
  keycloak-config.json: |
    {{-
    $resource := .Values.keycloak.resource | default (printf "%s-%s-spa" .Release.Namespace (include "chat-plus-plus.fullname" .))
    -}}
    {{-
    dict
      "auth-server-url" (required "keycloak.authServerUrl is required" .Values.keycloak.authServerUrl)
      "realm" (required "keycloak.realm is required" .Values.keycloak.realm)
      "resource" $resource
    | toPrettyJson | nindent 4
    }}
  API_URL: {{ required "api.url is required" .Values.api.url }}
