apiVersion: v2
name: nebari-chat
type: application
description: chat pack for nebari
version: "set-by-cd"
appVersion: "set-by-cd"
keywords:
  - nebari
home: https://github.com/nebari-dev/nebari-chat-pack
sources:
  - https://github.com/nebari-dev/nebari-chat-pack
maintainers:
  - name: OpenTeams
    email: info@openteams.com

dependencies:
  - name: ravnar
    repository: oci://quay.io/nebari/charts
    version: "0.0.10"
