apiVersion: v2
name: nebari-chat
type: application
description: chat pack for nebari
# tmp change to be used as is in an actual deployment, should NOT be merged with
version: "0.0.20-dev4"
appVersion: "0.0.20-dev4"
keywords:
  - nebari
home: https://github.com/nebari-dev/nebari-chat-pack
sources:
  - https://github.com/nebari-dev/nebari-chat-pack
maintainers:
  - name: OpenTeams
    email: info@openteams.com

dependencies:
  - name: ravnar
    repository: oci://quay.io/nebari/charts
    version: "0.0.6"
