services:
  
  hrafnar:
    image: quay.io/reiemp/hrafnar:latest
    platform: linux/amd64
    ports: 
      - "8751:8751"
    env_file:
      - ./dev-deps/hrafnar-config/.hrafnar.env
    volumes:
      - ./dev-deps/hrafnar-config/config.yml:/etc/hrafnar/config.yml
    restart: unless-stopped
    networks:
      - openteams

  postgres-mcp:
    image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:latest
    platform: linux/amd64
    command: toolbox --tools-file /config/tools.yml --address 0.0.0.0
    ports:
      - "8001:5000"
    env_file:
      - ./dev-deps/mcp-config/.mcp.env
    volumes:
      - ./dev-deps/mcp-config:/config
    networks:
      - openteams

networks:
  openteams:
    name: openteams
    driver: bridge