{{- if .Values.chatPlusPlus.enabled }}
{{- $component := "chat-plus-plus" }}
{{- include "nebari-chat.nebariapp" (dict
    "top" .
    "component" $component
    "service" (dict
      "name" (include "ravnar.component-name" (dict "top" . "component" $component))
      "port" .Values.chatPlusPlus.service.port
    )
    "nebariapp" .Values.chatPlusPlus.nebariapp
) }}
{{- end }}
