{{- $component := "ravnar-nebari" }}
{{- with include "nebari-chat.ravnarContextJson" . | fromJson }}
{{- include "nebari-chat.nebariapp" (dict
    "top" $
    "component" $component
    "service" (dict
      "name" (include "ravnar.fullname" .)
      "port" .Values.service.port
    )
    "nebariapp" $.Values.ravnarNebari.nebariapp
) }}
{{- end }}
