/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LogoutRouteImport } from './routes/logout';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history';
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat';

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute;
  '/logout': typeof LogoutRoute;
  '/chat': typeof AuthenticatedChatRoute;
  '/history': typeof AuthenticatedHistoryRoute;
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute;
  '/chat': typeof AuthenticatedChatRoute;
  '/history': typeof AuthenticatedHistoryRoute;
  '/': typeof AuthenticatedIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/logout': typeof LogoutRoute;
  '/_authenticated/chat': typeof AuthenticatedChatRoute;
  '/_authenticated/history': typeof AuthenticatedHistoryRoute;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/logout' | '/chat' | '/history';
  fileRoutesByTo: FileRoutesByTo;
  to: '/logout' | '/chat' | '/history' | '/';
  id:
    | '__root__'
    | '/_authenticated'
    | '/logout'
    | '/_authenticated/chat'
    | '/_authenticated/history'
    | '/_authenticated/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LogoutRoute: typeof LogoutRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout';
      path: '/logout';
      fullPath: '/logout';
      preLoaderRoute: typeof LogoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/history': {
      id: '/_authenticated/history';
      path: '/history';
      fullPath: '/history';
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/chat': {
      id: '/_authenticated/chat';
      path: '/chat';
      fullPath: '/chat';
      preLoaderRoute: typeof AuthenticatedChatRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute;
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LogoutRoute: LogoutRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
