/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SessionsRouteImport } from './routes/sessions';
import { Route as MemoryRouteImport } from './routes/memory';
import { Route as KnowledgeRouteImport } from './routes/knowledge';
import { Route as ChatRouteImport } from './routes/chat';
import { Route as IndexRouteImport } from './routes/index';
import { Route as TutorRouteImport } from './routes/tutor';
import { Route as CalendarRouteImport } from './routes/calendar';
import { Route as TeacherPlanningRouteImport } from './routes/teacher-planning';
import { Route as ClassOverviewRouteImport } from './routes/class-overview';
import { Route as CounselorDashboardRouteImport } from './routes/counselor-dashboard';
import { Route as PrincipalAnalyticsRouteImport } from './routes/principal-analytics';
import { Route as LoginRouteImport } from './routes/login';

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any);
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any);
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any);
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any);
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any);
const TeacherPlanningRoute = TeacherPlanningRouteImport.update({
  id: '/teacher-planning',
  path: '/teacher-planning',
  getParentRoute: () => rootRouteImport,
} as any);
const ClassOverviewRoute = ClassOverviewRouteImport.update({
  id: '/class-overview',
  path: '/class-overview',
  getParentRoute: () => rootRouteImport,
} as any);
const CounselorDashboardRoute = CounselorDashboardRouteImport.update({
  id: '/counselor-dashboard',
  path: '/counselor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const PrincipalAnalyticsRoute = PrincipalAnalyticsRouteImport.update({
  id: '/principal-analytics',
  path: '/principal-analytics',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/chat': typeof ChatRoute;
  '/calendar': typeof CalendarRoute;
  '/class-overview': typeof ClassOverviewRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/memory': typeof MemoryRoute;
  '/teacher-planning': typeof TeacherPlanningRoute;
  '/principal-analytics': typeof PrincipalAnalyticsRoute;
  '/sessions': typeof SessionsRoute;
  '/tutor': typeof TutorRoute;
  '/counselor-dashboard': typeof CounselorDashboardRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/chat': typeof ChatRoute;
  '/calendar': typeof CalendarRoute;
  '/class-overview': typeof ClassOverviewRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/memory': typeof MemoryRoute;
  '/teacher-planning': typeof TeacherPlanningRoute;
  '/principal-analytics': typeof PrincipalAnalyticsRoute;
  '/sessions': typeof SessionsRoute;
  '/tutor': typeof TutorRoute;
  '/counselor-dashboard': typeof CounselorDashboardRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/chat': typeof ChatRoute;
  '/calendar': typeof CalendarRoute;
  '/class-overview': typeof ClassOverviewRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/memory': typeof MemoryRoute;
  '/teacher-planning': typeof TeacherPlanningRoute;
  '/principal-analytics': typeof PrincipalAnalyticsRoute;
  '/sessions': typeof SessionsRoute;
  '/tutor': typeof TutorRoute;
  '/counselor-dashboard': typeof CounselorDashboardRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/calendar' | '/chat' | '/class-overview' | '/counselor-dashboard' | '/knowledge' | '/login' | '/memory' | '/principal-analytics' | '/sessions' | '/teacher-planning' | '/tutor';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/calendar' | '/chat' | '/class-overview' | '/counselor-dashboard' | '/knowledge' | '/login' | '/memory' | '/principal-analytics' | '/sessions' | '/teacher-planning' | '/tutor';
  id: '__root__' | '/' | '/calendar' | '/chat' | '/class-overview' | '/counselor-dashboard' | '/knowledge' | '/login' | '/memory' | '/principal-analytics' | '/sessions' | '/teacher-planning' | '/tutor';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChatRoute: typeof ChatRoute;
  CalendarRoute: typeof CalendarRoute;
  ClassOverviewRoute: typeof ClassOverviewRoute;
  KnowledgeRoute: typeof KnowledgeRoute;
  MemoryRoute: typeof MemoryRoute;
  TeacherPlanningRoute: typeof TeacherPlanningRoute;
  PrincipalAnalyticsRoute: typeof PrincipalAnalyticsRoute;
  SessionsRoute: typeof SessionsRoute;
  TutorRoute: typeof TutorRoute;
  CounselorDashboardRoute: typeof CounselorDashboardRoute;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/calendar': {
      id: '/calendar';
      path: '/calendar';
      fullPath: '/calendar';
      preLoaderRoute: typeof CalendarRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/sessions': {
      id: '/sessions';
      path: '/sessions';
      fullPath: '/sessions';
      preLoaderRoute: typeof SessionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/memory': {
      id: '/memory';
      path: '/memory';
      fullPath: '/memory';
      preLoaderRoute: typeof MemoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/class-overview': {
      id: '/class-overview';
      path: '/class-overview';
      fullPath: '/class-overview';
      preLoaderRoute: typeof ClassOverviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/knowledge': {
      id: '/knowledge';
      path: '/knowledge';
      fullPath: '/knowledge';
      preLoaderRoute: typeof KnowledgeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/teacher-planning': {
      id: '/teacher-planning';
      path: '/teacher-planning';
      fullPath: '/teacher-planning';
      preLoaderRoute: typeof TeacherPlanningRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chat': {
      id: '/chat';
      path: '/chat';
      fullPath: '/chat';
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/principal-analytics': {
      id: '/principal-analytics';
      path: '/principal-analytics';
      fullPath: '/principal-analytics';
      preLoaderRoute: typeof PrincipalAnalyticsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/tutor': {
      id: '/tutor';
      path: '/tutor';
      fullPath: '/tutor';
      preLoaderRoute: typeof TutorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/counselor-dashboard': {
      id: '/counselor-dashboard';
      path: '/counselor-dashboard';
      fullPath: '/counselor-dashboard';
      preLoaderRoute: typeof CounselorDashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CalendarRoute: CalendarRoute,
  ClassOverviewRoute: ClassOverviewRoute,
  KnowledgeRoute: KnowledgeRoute,
  MemoryRoute: MemoryRoute,
  TeacherPlanningRoute: TeacherPlanningRoute,
  PrincipalAnalyticsRoute: PrincipalAnalyticsRoute,
  SessionsRoute: SessionsRoute,
  TutorRoute: TutorRoute,
  CounselorDashboardRoute: CounselorDashboardRoute,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
