/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SessionsRouteImport } from './routes/sessions';
import { Route as MetricsRouteImport } from './routes/metrics';
import { Route as MemoriesRouteImport } from './routes/memories';
import { Route as KnowledgeRouteImport } from './routes/knowledge';
import { Route as ChatRouteImport } from './routes/chat';
import { Route as IndexRouteImport } from './routes/index';

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any);
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any);
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any);
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any);
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/chat': typeof ChatRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/memories': typeof MemoriesRoute;
  '/metrics': typeof MetricsRoute;
  '/sessions': typeof SessionsRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/chat': typeof ChatRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/memories': typeof MemoriesRoute;
  '/metrics': typeof MetricsRoute;
  '/sessions': typeof SessionsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/chat': typeof ChatRoute;
  '/knowledge': typeof KnowledgeRoute;
  '/memories': typeof MemoriesRoute;
  '/metrics': typeof MetricsRoute;
  '/sessions': typeof SessionsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/chat'
    | '/knowledge'
    | '/memories'
    | '/metrics'
    | '/sessions';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/chat' | '/knowledge' | '/memories' | '/metrics' | '/sessions';
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/knowledge'
    | '/memories'
    | '/metrics'
    | '/sessions';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChatRoute: typeof ChatRoute;
  KnowledgeRoute: typeof KnowledgeRoute;
  MemoriesRoute: typeof MemoriesRoute;
  MetricsRoute: typeof MetricsRoute;
  SessionsRoute: typeof SessionsRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions';
      path: '/sessions';
      fullPath: '/sessions';
      preLoaderRoute: typeof SessionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/metrics': {
      id: '/metrics';
      path: '/metrics';
      fullPath: '/metrics';
      preLoaderRoute: typeof MetricsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/memories': {
      id: '/memories';
      path: '/memories';
      fullPath: '/memories';
      preLoaderRoute: typeof MemoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/knowledge': {
      id: '/knowledge';
      path: '/knowledge';
      fullPath: '/knowledge';
      preLoaderRoute: typeof KnowledgeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chat': {
      id: '/chat';
      path: '/chat';
      fullPath: '/chat';
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  KnowledgeRoute: KnowledgeRoute,
  MemoriesRoute: MemoriesRoute,
  MetricsRoute: MetricsRoute,
  SessionsRoute: SessionsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
